baseURL = "https://kukode.in/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Kukode.in - Jasa Pembuatan Website & Maintenance SEO Jogja"

publishDir = "docs"
disqusShortname = "ahmadmzakki"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Pricing"
url = "#pricing"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About Us"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Contact Us"
url = "contact"
weight = 2
[[menu.sitemap]]
name = "Our Blog"
url = "blog"
weight = 3
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "faq"
weight = 4
[[menu.sitemap]]
name = "Privacy & Policy"
url = "privacy-policy"
weight = 5

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "© Copyright 2021 • Kukode.in - Jasa Pembuatan Website & SEO Jogja"
footerLogo = "images/site-navigation/logo_white.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "G-81NBPGLTL5"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Jl. Kepuh Permai No.D35, RT.05/RW.23, Gondang Legi, Wedomartani, Ngemplak, Sleman, Yogyakarta 55584."
email = "kukodein@gmail.com"
openingHours = "Open from 09.00 AM to 04.00 PM"
phone = "+62 877-2626-5660"

[params.map]
APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
latitude = "-7.7341006"
longitude = "110.4386247"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://fb.me/kukodein"
weight = 1
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/kukode.in"
weight = 2
[[params.social]]
icon = "fa-telegram"
url = "https://t.me/kukodein"
weight = 3
[[params.social]]
icon = "fa-whatsapp"
url = "https://api.whatsapp.com/send?phone=6287726265660"
weight = 4
[[params.social]]
icon = "fa-github"
url = "https://github.com/kukodein"
weight = 5
[[params.social]]
icon = "fa fa-youtube-play"
url = "https://www.youtube.com/channel/UC-sqh84XZ6TO26T_S_B2S0g"
weight = 6

uglyurls = true
[permalinks]
  post = ":filename"